language: node_js

node_js:
  - 'stable'

addons:
  postgresql: 'stable'

services:
  - postgresql

before_install:
  - yarn install

before_script:
  - psql -c 'create database restaurante_db;' -U postgres

after_success: npm run coverage